test_name: Регистрация

marks:
  - usefixtures:
      - generate_random_email

stages:
  - name: "Проверить 201 Minimal /auth/register"
    request:
      url: "{BASE_URL}/auth/register"
      method: POST
      json:
        email: "{generate_random_email}"
        password: "V3rYH@rdP@$sW0Rd!1!11!!!"
        fullName: "Igor Bailyuk"
    response:
      status_code: 201
      json:
        expiresIn: 3600
        user:
          email: "{generate_random_email}"
          fullName: "Igor Bailyuk"
          role: USER
          isActive: true

  - name: "Проверить 400 /auth/register"
    request:
      url: "{BASE_URL}/auth/register"
      method: POST
      headers:
        content-type: application/json
      data: '{{"dsadsa": "dsadas"'
    response:
      status_code: 400
      json:
        code: BAD_REQUEST
        path: /api/v1/auth/register

  - name: "Проверить 422 (no fullName) /auth/register"
    request:
      url: "{BASE_URL}/auth/register"
      method: POST
      json:
        email: "{generate_random_email}"
        password: "V3rYH@rdP@$sW0Rd!1!11!!!"
    response:
      status_code: 422
      json:
        code: VALIDATION_FAILED
        path: /api/v1/auth/register

  - name: "Проверить 422 (no email) /auth/register"
    request:
      url: "{BASE_URL}/auth/register"
      method: POST
      json:
        password: "V3rYH@rdP@$sW0Rd!1!11!!!"
        fullName: "Igor Bailyuk"
    response:
      status_code: 422
      json:
        code: VALIDATION_FAILED
        path: /api/v1/auth/register

  - name: "Проверить 422 (no password) /auth/register"
    request:
      url: "{BASE_URL}/auth/register"
      method: POST
      json:
        email: "{generate_random_email}"
        fullName: "Igor Bailyuk"
    response:
      status_code: 422
      json:
        code: VALIDATION_FAILED
        path: /api/v1/auth/register
